apiVersion: v1
kind: Service
metadata:
  name: fraud-api-lb
  labels:
    app: fraud-api
spec:
  type: LoadBalancer
  selector:
    app: fraud-api
  ports:
    - port: 80                # Public port
      targetPort: 8200        # Container port
      protocol: TCP
      name: http
